version: '3.1'

services:
  api:
    image: taskmanager-api
    container_name: task-api
    build:
      context: .
    ports:
      - '3001:3000'
    depends_on:
      - postgres
    volumes:
      - ./src:/usr/src/app/src
    networks:
      - default
    env_file:
      - .env

  postgres:
    image: postgres:10.4-alpine
    container_name: taskmanager-postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
    env_file:
      - .env

  pgadmin:
    image: dpage/pgadmin4
    container_name: taskmanager-pgadmin
    ports:
      - '8888:80'
    volumes:
      - admin_data:/var/lib/pgadmin
    env_file:
      - .env

volumes:
  db_data:
  admin_data:

networks:
  postgres:
    driver: bridge
  default:
    name: taskmanager-net
    driver: bridge
